// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar for the AI Engineering Book
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introduction to AI',
      items: [
        'introduction-to-ai/index',
      ],
    },
    {
      type: 'category',
      label: 'Understanding LLMs',
      items: [
        'understanding-llms/index',
      ],
    },
    {
      type: 'category',
      label: 'Prompt Engineering',
      items: [
        'prompt-engineering/index',
      ],
    },
    {
      type: 'category',
      label: 'Spec-Driven Development',
      items: [
        'spec-driven-development/index',
      ],
    },
    {
      type: 'category',
      label: 'Building AI Projects',
      items: [
        'building-ai-projects/index',
      ],
    },
    {
      type: 'category',
      label: 'Deploying AI Apps',
      items: [
        'deploying-ai-apps/index',
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus + AI Book Workflow',
      items: [
        'docusaurus-ai-book-workflow/index',
      ],
    },
  ],
};

export default sidebars;
